{
 "title": "ASP.NET Core Metrics",
 "tags": [
  "aspnet",
  "dotnet",
  "prometheus"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Response Time (avg)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (histogram)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "95th percentile"
    }
   ]
  }
 ]
}