services:
  dotnet:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - monitoring
    volumes:
      - .:/workspace

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning

volumes:
  grafana-storage:

networks:
  monitoring:
